# Class 11 Numpy as np

In [1]:
import numpy as np

CREATING ARRAYS:

In [2]:
a = np.array([7,9,0])

In [3]:
a

array([7, 9, 0])

In [4]:
b = np.array([[6,7,8],[8,9,0] ], dtype=float)

In [5]:
b

array([[6., 7., 8.],
       [8., 9., 0.]])

In [6]:
c = np.array([[6,7,8],[8,9,0],[0,8,5] ], dtype=int)

In [7]:
c

array([[6, 7, 8],
       [8, 9, 0],
       [0, 8, 5]])

INITIAL PLACEHOLDERS:

In [8]:
np.zeros([1,4,6]) # creating an array of zeros

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [9]:
np.ones([2,5,7] , dtype = int)  # creating an array of ones

array([[[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]]])

In [10]:
d = np.arange(10,29,2)

In [11]:
d

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [12]:
np.linspace(0,2,8)

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

In [13]:
np.linspace(0,1,8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [14]:
e = np.full((2,5),8)

In [15]:
e

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [16]:
f = np.eye(3 , dtype = int) # creating identity matrix

In [17]:
f

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
np.random.random((3,3))

array([[0.85754399, 0.46332269, 0.81229168],
       [0.80681104, 0.87599816, 0.28266564],
       [0.58258462, 0.41796373, 0.48174744]])

In [19]:
arr= np.random.randint(10,20,(3,3))

In [20]:
arr

array([[11, 18, 15],
       [17, 15, 19],
       [12, 17, 16]])

In [21]:
np.random.random((4,4))

array([[0.83827138, 0.94442934, 0.9864344 , 0.84802209],
       [0.84004106, 0.76705543, 0.01856453, 0.54857877],
       [0.71824406, 0.64161107, 0.8851662 , 0.93879405],
       [0.82862871, 0.97906291, 0.21407115, 0.69065944]])

In [22]:
np.empty((3,2))

array([[6., 7.],
       [8., 8.],
       [9., 0.]])

In [23]:
a.shape

(3,)

In [24]:
len(a)

3

In [25]:
a.ndim

1

In [26]:
a.size

3

In [27]:
a.dtype

dtype('int32')

In [28]:
a.dtype.name

'int32'

In [29]:
a.astype(int) # change data type

array([7, 9, 0])

np.int64
np.float
np.complex
np.bool
np.object
np.string_
np.unicode_


SOLVING AND LOADING ON DISK:

In [30]:
np.save("my_array",a)

In [31]:
np.save("my_array",b)

In [32]:
np.savez("array.npz",a,b)

In [33]:
np.load("my_array.npy")

array([[6., 7., 8.],
       [8., 9., 0.]])

SOLVING & LOADING TEXT FILES:

In [34]:
from numpy import loadtxt

In [35]:
raw_data = open("desktop/Attribute_dataset.csv")

In [36]:
data = loadtxt(raw_data,delimiter = ",",dtype= str)

In [37]:
data

array([['Style', 'Price', 'Rating', ..., 'Decoration', 'Pattern Type',
        'Recommendation'],
       ['Sexy', 'Low', '4.6', ..., 'ruffles', 'animal', '1'],
       ['Casual', 'Low', '0', ..., 'ruffles', 'animal', '0'],
       ...,
       ['Casual', 'Average', '4.7', ..., 'lace', 'solid', '1'],
       ['Casual', 'Average', '4.6', ..., 'applique', 'print', '1'],
       ['Casual', 'Low', '4.4', ..., 'lace', 'solid', '0']], dtype='<U15')

In [38]:
type(data)

numpy.ndarray

In [39]:
data.shape

(480, 12)

In [40]:
data[0]

array(['Style', 'Price', 'Rating', 'Size', 'Season', 'NeckLine',
       'SleeveLength', 'Material', 'FabricType', 'Decoration',
       'Pattern Type', 'Recommendation'], dtype='<U15')

In [41]:
data[5]

array(['cute', 'Low', '4.5', 'M', 'Summer', 'o-neck', 'butterfly',
       'chiffonfabric', 'chiffon', 'bow', 'dot', '0'], dtype='<U15')

In [42]:
data[1]

array(['Sexy', 'Low', '4.6', 'M', 'Summer', 'o-neck', 'sleevless', 'null',
       'chiffon', 'ruffles', 'animal', '1'], dtype='<U15')

In [43]:
y= np.loadtxt("desktop/my_file.txt")

In [44]:
y

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.]])

In [45]:
y= np.genfromtxt("desktop/my_file.txt")

In [46]:
y

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.]])

In [47]:
y= np.genfromtxt("desktop/my_file.txt",filling_values = 5,skip_header=1,skip_footer=1)

In [48]:
print(y)

[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]]


In [49]:
g= np.fromfile("desktop/my_file.txt",count=-1)

In [50]:
print(g)

[1.42646471e-153 1.72480289e-153 2.81231600e-077 1.29038135e-057
 2.38262937e-038 1.19626294e-153 1.50104926e-153 1.79938744e-153
 4.58094356e-072 8.45868240e-053 1.56185615e-033 1.27729552e-153
 1.57563380e-153 1.87397198e-153 3.00295427e-067 5.54481850e-048
 7.00529198e-077 1.35188017e-153 1.65021835e-153 3.69017309e-245
 1.96849090e-062 3.63472808e-043 2.96618322e-260 1.42646471e-153
 1.72480289e-153]


In [51]:
import numpy as np

In [52]:
o = np.arange(1,101)

In [53]:
print(o)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [54]:
p = np.savetxt("array.csv",o,delimiter=",",fmt="%d")

In [55]:
m= np.arange(1,101)

In [56]:
m.tofile("array1.csv" ,sep =",",format="%d")

Routines for reading data:
    
1.np.loadtxt()= Load data from text file.
y = np.loadtxt("test.txt")
print(y)

2.np.genfromtxt() = oad data from text file ,with missing values handled as specified.

parameter        Description

filename         file,filename,list,or generator to read
delimiter        the string used to separate values
missing_values   the set of strings corresponding to missing data
filling_values   the set of values to be used as default when the data are missing.
g = np.genfromtxt("missing_data.txt")
g = np.genfromtxt("missing_data.txt",filling_values=5,usecols=(1,-1))
g = np.genfromtxt("missing_data.txt",filling_values=5,skip_header=1,skip_footer=1)
print(g)

3.np.fromfile()= construct array from data in a text or binary file.
g=np.fromfile("missing_values.csv",count=-1,sep=",")

4. np.savetxt()= save data to txt file.
   o = np.arange(1,101)
   p = np.savetxt("array.csv",o,delimiter=",",fmt="%d")
    
5. np.tofile()= write array to the file as txt.
m= np.arange(1,101)
m.tofile("array1.csv" ,sep =",",format="%d")

# ARRAY MATHEMATICS:


In [57]:
a

array([7, 9, 0])

In [58]:
b

array([[6., 7., 8.],
       [8., 9., 0.]])

In [59]:
c

array([[6, 7, 8],
       [8, 9, 0],
       [0, 8, 5]])

In [60]:
d

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [63]:
a+b

array([[13., 16.,  8.],
       [15., 18.,  0.]])

In [66]:
b+2+8

array([[16., 17., 18.],
       [18., 19., 10.]])

In [69]:
a-b

array([[ 1.,  2., -8.],
       [-1.,  0.,  0.]])

In [70]:
a-b+5

array([[ 6.,  7., -3.],
       [ 4.,  5.,  5.]])

In [71]:
a*b

array([[42., 63.,  0.],
       [56., 81.,  0.]])

In [72]:
a*b+2

array([[44., 65.,  2.],
       [58., 83.,  2.]])

In [76]:
a/b

C:\Users\ACER\AppData\Local\Temp\ipykernel_11052\1348051284.py:1: RuntimeWarning: invalid value encountered in true_divide
  a/b


array([[1.16666667, 1.28571429, 0.        ],
       [0.875     , 1.        ,        nan]])

In [77]:
np.divide(a,b)

C:\Users\ACER\AppData\Local\Temp\ipykernel_11052\2626738034.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.divide(a,b)


array([[1.16666667, 1.28571429, 0.        ],
       [0.875     , 1.        ,        nan]])

In [78]:
np.add(a,b)

array([[13., 16.,  8.],
       [15., 18.,  0.]])

In [79]:
np.multiply(a,b)

array([[42., 63.,  0.],
       [56., 81.,  0.]])

In [80]:
np.subtract(a,b)

array([[ 1.,  2., -8.],
       [-1.,  0.,  0.]])

In [82]:
np.exp(a)

array([1.09663316e+03, 8.10308393e+03, 1.00000000e+00])

In [83]:
np.sqrt(a)

array([2.64575131, 3.        , 0.        ])

In [84]:
np.sin(a)

array([0.6569866 , 0.41211849, 0.        ])

In [85]:
np.cos(b)

array([[ 0.96017029,  0.75390225, -0.14550003],
       [-0.14550003, -0.91113026,  1.        ]])

In [88]:
np.log(b)

C:\Users\ACER\AppData\Local\Temp\ipykernel_11052\4200754868.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(b)


array([[1.79175947, 1.94591015, 2.07944154],
       [2.07944154, 2.19722458,       -inf]])

In [89]:
np.tan(a)

array([ 0.87144798, -0.45231566,  0.        ])

In [91]:
g=[2,4,5]

In [98]:
a.dot(g)

50

In [99]:
a


array([7, 9, 0])

In [100]:
g

[2, 4, 5]

COPYING  ARRAYS:

In [103]:
h= a.view() # create a view

In [104]:
h

array([7, 9, 0])

In [105]:
np.copy(a)

array([7, 9, 0])

In [106]:
h=a.copy() # create a deep view

In [107]:
h

array([7, 9, 0])

SORTING ARRAYS:

In [113]:
a.sort(axis=0)

In [114]:
b.sort(axis=0)

In [115]:
a

array([0, 7, 9])

In [116]:
b

array([[6., 7., 0.],
       [8., 9., 8.]])

ARRAY MANIPULATION:

TRANSPOSING ARRAY:

In [125]:
i= np.transpose(b)

In [126]:
i

array([[6., 8.],
       [7., 9.],
       [0., 8.]])

CHANGING ARRAYS SHAPE:

In [128]:
b.ravel()

array([6., 7., 0., 8., 9., 8.])

In [136]:
b.reshape(-1,2)

array([[6., 7.],
       [0., 8.],
       [9., 8.]])

In [137]:
b.reshape(1,-2)

array([[6., 7., 0., 8., 9., 8.]])

ADDING AND REMOVING ELEMENTS:

In [158]:
h= b.copy()

In [159]:
h

array([[6., 7., 0.],
       [8., 9., 8.]])

In [168]:
np.append(a,b)

array([0., 7., 9., 6., 7., 0., 8., 9., 8.])

In [176]:
np.insert(a,3,6)

array([0, 7, 9, 6])

In [180]:
np.delete(a,[1])

array([0, 9])

COMBINING ARRAYS:

In [185]:
np.concatenate((a,g)) # must be of same dimension

array([0, 7, 9, 2, 4, 5])

In [186]:
np.vstack((a,g))

array([[0, 7, 9],
       [2, 4, 5]])

In [187]:
np.hstack((a,g))

array([0, 7, 9, 2, 4, 5])

SPLITTING ARRAY:

In [191]:
np.hsplit(a,3)

[array([0]), array([7]), array([9])]

In [203]:
np.vsplit(b,2)

[array([[6., 7., 0.]]), array([[8., 9., 8.]])]

In [207]:
np.vsplit(c,1)

[array([[6, 7, 8],
        [8, 9, 0],
        [0, 8, 5]])]

SUBSETTING:

In [218]:
b[0,1]

7.0

In [211]:
b

array([[6., 7., 0.],
       [8., 9., 8.]])

SLICING:

In [221]:
a[0:2]

array([0, 7])

In [220]:
a

array([0, 7, 9])

In [231]:
b[0:1]

array([[6., 7., 0.]])

BOOLEAN INDEXING:

In [234]:
a[a<10]

array([0, 7, 9])

In [235]:
b[b<10]

array([6., 7., 0., 8., 9., 8.])